name: Example with Inputs

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose the environment"
        required: true
        default: "dev"

jobs:
  print-input:
    runs-on: ubuntu-latest
    steps:
      - name: Display Environment
        run: |
          echo "Deploying to environment: ${{ github.event.inputs.environment }}"
